---
data_dir: "/home/matyas/Documents/UFAL/PMLTQ_WEB/REP/perl-pmltq_CONV_SCRIPT/perl-pmltq/t/treebanks/pdt20_sample_small/data"
resources: "/home/matyas/Documents/UFAL/PMLTQ_WEB/REP/perl-pmltq_CONV_SCRIPT/perl-pmltq/t/treebanks/pdt20_sample_small/resources" # main directory with PML schemas

db:
  name: test_pdt20_sample_small
  host: localhost
  port: 15432
  user: pmltq_test
  password: tesTpass

layers: # description of all data layers
  - name: adata
    data: ./*.a.gz
    resources:
      - extra_resource
  - name: tdata
    data: ./*.t.gz
    for_each_tree: "PMLTQ::PML2BASE::PDT::DumpData::tdata::dump_eparent"
    for_schema: "PMLTQ::PML2BASE::PDT::MakeTable::tdata::mk_extra_tables"
    related-schema:
      - /home/matyas/Documents/UFAL/PMLTQ_WEB/REP/perl-pmltq_CONV_SCRIPT/perl-pmltq/script/DATA/pdt20_mini/resources/adata_schema.xml
      - /home/matyas/Documents/UFAL/PMLTQ_WEB/REP/perl-pmltq_CONV_SCRIPT/perl-pmltq/script/DATA/pdt20_mini/data/vallex_pml/vallex_schema.xml
    references:
      t-a/aux.rf: "adata:a-node"  # t-a/aux.rf=adata:a-node
      t-a/lex.rf: "adata:a-node"
      t-root/atree.rf: "adata:a-root"
      t-node/coref_gram.rf: t-node  # t-node/coref_gram.rf=t-node
      t-node/coref_text.rf: t-node
      t-node/compl.rf: t-node
      t-node/val_frame.rf: "-"

