---
data_dir: "./data"
resources: "./resources" # main directory with PML schemas

extension: PDT

db:
  name: pdt20_sample_small
  host: localhost
  port: 15432
  user: pmltq_test
  password: tesTpass

layers: # description of all data layers
  - name: adata
    data: ./*.a.gz
    resources:
      - extra_resource
  - name: tdata
    data: ./*.t.gz
    related-schema:
      - "./resources/adata_schema.xml"
      - "./data/vallex_pml/vallex_schema.xml"
    references:
      t-a/aux.rf: "adata:a-node"  # t-a/aux.rf=adata:a-node
      t-a/lex.rf: "adata:a-node"
      t-root/atree.rf: "adata:a-root"
      t-node/coref_gram.rf: t-node  # t-node/coref_gram.rf=t-node
      t-node/coref_text.rf: t-node
      t-node/compl.rf: t-node
      t-node/val_frame.rf: "-"

